version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=3_1_4_work_with_docker'
    ports:
      - "5443:5432"

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"